### PR TITLE
refactor(aws): avoid using data source resources

### PR DESCRIPTION
**Pull request by afiune**
# Breaking Change Release
We have generated an internal announcement that will be delivered to our
customers using our Terraform provider and modules, additionally we have
planned to **release this change next Wednesday 9/9/2020**

**BREAKING-CHANGE This might be a breaking change for our current users!**

Our strategy to use a data source was to access the ARN of the
generated IAM Role, or the provided IAM Role name if the user
decides not to create it. This caused confusions since the data
resource will generate a constant change while running terraform
apply, so we are trying not to use this pattern anymore.

Example of a second terraform apply:
```
  ~ resource "aws_iam_policy" "cross_account_policy" {
      ~ policy      = jsonencode(...) -> (known after apply)
  }

  ~ resource "lacework_integration_aws_cfg" "default" {
      ~ credentials {
            external_id = "..."
          ~ role_arn    = "..." -> (known after apply)
      }
  }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

  ...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

## Users now MUST provide ARN for IAM Role and/or S3 bucket

If a user was using one of the `use_existing_iam_role` or `use_existing_cloudtrail` variables,
they will have to update their Terraform plans to pass not only the name but the ARN as well.

### Existing IAM Role
**Before:**
```hcl
provider "lacework" { }

provider "aws" { }

module "aws_cloudtrail" {
	source = "git::https://github.com/lacework/terraform-provisioning.git//aws/modules/cloudtrail?ref=master"

	# Use an existing IAM role
	use_existing_iam_role = true
	iam_role_name         = "lw-existing-role"
	iam_role_external_id  = "1GrDkEZV5VJ@=nLm"
}
```
**Now:**
```hcl
provider "lacework" { }

provider "aws" { }

module "aws_cloudtrail" {
	source = "git::https://github.com/lacework/terraform-provisioning.git//aws/modules/cloudtrail?ref=master"

	# Use an existing IAM role
	use_existing_iam_role = true
	iam_role_arn          = "arn:aws:iam::123456789012:role/lw-existing-role"  // <-- NEW! Must be provided
	iam_role_name         = "lw-existing-role"
	iam_role_external_id  = "1GrDkEZV5VJ@=nLm"
}
```

### Existing CloudTrail
**Before:**
```hcl
provider "lacework" { }

provider "aws" { }

module "aws_cloudtrail" {
	source = "git::https://github.com/lacework/terraform-provisioning.git//aws/modules/cloudtrail?ref=master"

	# Use an existing CloudTrail
	use_existing_cloudtrail    = true
	bucket_name                = "lacework-ct-bucket-8805c0bf"
	sns_topic_name             = "lacework-ct-sns-8805c0bf"
}
```
**Now:**
```hcl
provider "lacework" { }

provider "aws" { }

module "aws_cloudtrail" {
	source = "git::https://github.com/lacework/terraform-provisioning.git//aws/modules/cloudtrail?ref=master"

	# Use an existing CloudTrail
	use_existing_cloudtrail    = true
	bucket_arn                 = "arn:aws:s3:::lacework-ct-bucket-8805c0bf"  // <-- NEW! Must be provided
	bucket_name                = "lacework-ct-bucket-8805c0bf"
	sns_topic_name             = "lacework-ct-sns-8805c0bf"
}
```

Signed-off-by: Salim Afiune Maya <afiune@lacework.net>

### CODE REVIEW

**Comment by afiune** [comment]
Testing this code on our internal test environment `CUSTOMERDEMO`:
```
$ terraform apply

  # module.tech_ally_aws_config.module.lacework_cfg_iam_role.data.aws_iam_policy_document.lacework_assume_role_policy[0] will be read during apply
  # module.tech_ally_aws_config.module.lacework_cfg_iam_role.aws_iam_role.lacework_iam_role[0] will be updated in-place
  # module.tech_ally_aws_config.module.lacework_cfg_iam_role.time_sleep.wait_5_seconds will be destroyed
  # module.tech_ally_aws_cloudtrail.module.lacework_ct_iam_role.time_sleep.wait_5_seconds will be destroyed
  # module.tech_ally_aws_cloudtrail.module.lacework_ct_iam_role.random_string.external_id[0] will be destroyed
  # module.tech_ally_aws_cloudtrail.aws_iam_policy.cross_account_policy will be updated in-place

Plan: 0 to add, 2 to change, 3 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

   ...

Apply complete! Resources: 0 added, 0 changed, 3 destroyed.
```

Second terraform apply:
```
$ terraform apply
  # module.tech_ally_aws_cloudtrail.data.aws_s3_bucket.selected will be read during apply
  # (config refers to values not yet known)
 <= data "aws_s3_bucket" "selected"  {
    }

  # module.tech_ally_aws_cloudtrail.aws_iam_policy.cross_account_policy will be updated in-place
  ~ resource "aws_iam_policy" "cross_account_policy" {
      ~ policy      = jsonencode() -> (known after apply)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

We are missing one data source inside the CloudTrail module. Let's do it!

tenor-61862339

**Comment by afiune** [comment]
Running a new test of our internal environment:
```
$ terraform init --upgrade=true
Upgrading modules...

$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

tenor-222455129

**Comment by scottford-lw** [comment]
@afiune Couple of things...

1. Does this mean that a customer will need to provision in two steps...(1. Config (gets IAM ARN), 2. CloudTrail (pass IAM ARN from step 1)? 

2. Should we look to provide releases for these modules so customers can pin to versions?

**Comment by afiune** [comment]
@scottford-io 
1. No, they will provision the same way they are doing it today. Either Config or CloudTrail or both at once. Even if they start with CT and then move to Config! 🎉
2. YES YES YES! We should do that, start releases and document them as well as pointing our documentation to the latest release, but we will need to communicate to our customers since they all are pointing to `master`. Let us make a plan 💯

**Comment by alannix-lw** [comment]
@afiune 

I just tested this in my sandbox and it's 🔥 !  Just need to make sure existing prospects/customers are aware that they need to potentially provide the role ARN.

**Comment by afiune** [comment]
@alannix-lw Amazing!! Thank you so much for testing this code. Much appreciated!

tenor-24090911

**Comment by BillWeiss** [comment]
As a customer, I'd just like to +1 the thought of versioning these :) I was just asking for that in a success call.

**Comment by afiune** [comment]
@BillWeiss That is great feedback! Thank you for reaching out 

tenor-87764594

We are going to start versioning this repository this week, take a look at https://github.com/lacework/terraform-provisioning/pull/63

**Comment by afiune** [comment]
# Breaking Change Release
We have generated an internal announcement that will be delivered to our
customers using our Terraform provider and modules, additionally we have
planned to **release this change next Wednesday 9/9/2020**

**Comment by afiune** [comment]
tenor-71930271

**Pull request merged**
